### ISSUE TITLE
Fix the GRUB2 menu is not displayed at all on the GPD Pocket 2

### ISSUE THREAD

**Issue by zanjie1999** [wimpysworld/gpd-pocket2-ubuntu#3]
Add: 
`GRUB_GFXMODE=1200x1920x32`
`GRUB_GFXPAYLOAD_LINUX=keep`
to `/etc/default/grub`
and do `update-grub`

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/gpd-pocket2-ubuntu/commit/cd4bc2fdbece8aa0f0e0d33e3cc0b797190bf11e
