### ISSUE TITLE
how about Ubuntu MATE 18.04.2 LTS image?

### ISSUE THREAD

**Issue by trydofor** [wimpysworld/gpd-pocket2-ubuntu#8]
is this in progress?

> Ubuntu MATE 18.04 LTS image?
> When Ubuntu MATE 18.04.2 is released in February 2019 we will evaluate creating an image that supports the GPD Pocket and GPD Pocket 2. Ubuntu MATE 18.04.2 will include the hardware enablement stack from Ubuntu 18.10 and that should provide the bulk of the required hardware support.

**Comment by flexiondotorg** [comment]
Hi,

Yes, I have started this process. I am travelling next week but should have
updated images before the end of February. I'll keep you informed :-)

**Comment by trydofor** [comment]
thanks. have a nice trip :D

**Comment by trydofor** [comment]
should i use gpd-pocket-ubuntu-respin.sh to burn the 18.04.2 LTS iso
or wait for https://ubuntu-mate.org/download/ provided iso.

**Comment by flexiondotorg** [comment]
I will be releasing Ubuntu MATE 18.04.2 ISO images for GPD Pocket and GPD Pocket 2 in the next 48 hours. A number of improvements over the 18.10 images :smiley:

**Comment by flexiondotorg** [comment]
Images for 18.04.2 and 19.04 beta are available from the download page:

  * https://ubuntu-mate.org/download/

I'll be posting a blog in due course but you can find a summary of the GPD specific features on this page:

  * https://ubuntu-mate.org/gpd-pocket/
