### ISSUE TITLE
Does not rotate the screen at anypoint under Ubuntu 19.04 Daily 2019-03-18

### ISSUE THREAD

**Issue by duckunix** [wimpysworld/gpd-pocket2-ubuntu#9]
any pointers on where to start looking to help update this.  Last time I debugged weird X issues, systemd was round, so I am not sure where to go looking for the X startup messages anymore.

Downloaded the script (gpd-pocket-ubuntu.sh) and ran it as root with the 'enable' flag.  I can see where it updated the files correctly, but I get no rotation.

Let me know where to look, and I will give it a look to see if I can figure it out.

**Comment by duckunix** [comment]
I should note that the consoles are rotated, just not the X session.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/gpd-pocket2-ubuntu/commit/14a4b6ee9e5c095080c00568f391414750e83f85 and https://github.com/wimpysworld/gpd-pocket2-ubuntu/commit/efbfa20897427d36e0e3e1636ecc18e89e23b684
